backend:
  name: git-gateway
  repo: FrankEinshtain/pozsite
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: site
    label: Site
    folder: src/markdown
    format: frontmatter
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - {
          name: hero,
          label: Hero,
          widget: object,
          fields:
            [
              { label: Title, name: title, widget: string },
              { label: Subtitle, name: subtitle, widget: string },
              { label: 'Button URL', name: buttonurl, widget: string },
              { label: Background, name: background, widget: image },
            ],
        }
      - {
          name: whatwedo,
          label: 'What We Do',
          widget: 'list',
          allow_add: true,
          collapsed: false,
          fields:
            [
              { name: title, label: Title, widget: string },
              { name: icon, label: Icon, widget: image },
            ],
        }
      - {
          name: competences,
          label: competences,
          widget: 'list',
          allow_add: true,
          collapsed: false,
          fields:
            [
              { name: title, label: Title, widget: string },
              {
                name: icons,
                label: Icons,
                widget: 'list',
                allow_add: true,
                collapsed: false,
                field: { name: icon, label: Icon, widget: image },
              },
            ],
        }
      - {
          name: references,
          label: References,
          widget: object,
          fields:
            [
              { name: buttonurl, label: 'Button Url', widget: string },
              {
                name: referencelist,
                label: 'Reference List',
                widget: 'list',
                allow_add: true,
                collapsed: false,
                fields:
                  [
                    { name: name, label: name, widget: string },
                    { name: text, label: text, widget: string },
                    { name: position, label: position, widget: string },
                    { name: photo, label: photo, widget: image },
                  ],
              },
            ],
        }
      - {
          name: whychooseus,
          label: 'Why Choose Us',
          widget: list,
          fields:
            [
              { name: text, label: text, widget: string },
              { name: textbold, label: 'Text Bold', widget: string },
              { name: buttonurl, label: 'Button URL', widget: string },
            ],
        }
      - {
          name: team,
          label: 'Out team',
          widget: 'list',
          allow_add: true,
          collapsed: false,
          fields:
            [
              { name: name, label: name, widget: string },
              { name: position, label: position, widget: string },
              { name: photo, label: photo, widget: image },
            ],
        }
      - {
          name: vacancies,
          label: Vacancies,
          widget: object,
          fields:
            [
              { name: title, label: Title, widget: string },
              { name: image, label: image, widget: image },
              {
                name: advantages,
                label: advantages,
                widget: 'list',
                allow_add: true,
                collapsed: false,
                field: { name: item, label: 'Advantage Item', widget: string },
              },
              {
                name: vacancylist,
                label: 'Vacancy List',
                widget: list,
                allow_add: true,
                collapsed: false,
                fields:
                  [
                    { name: title, label: title, widget: string },
                    { name: icon, label: icon, widget: image },
                    { name: bullit, label: bullit, widget: string },
                    {
                      name: requirements,
                      label: requirements,
                      widget: 'list',
                      allow_add: true,
                      collapsed: false,
                      fields:
                        [
                          {
                            name: item,
                            label: 'Requirement Item',
                            widget: string,
                          },
                        ],
                    },
                  ],
              },
            ],
        }
      - { name: map, label: Map, widget: image }
      - { name: contactimage, label: 'ContactImage', widget: image }
